# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-raspbian-image:
    machine:
      image: circleci/classic:latest

    working_directory: ~/TreasureBoxBrailleApps

    steps:
      - run:
          name: "Create a Raspberry Pi custom image with SCALP"
          command: |
            sudo apt install zip unzip
            sudo apt-get install jq

            # Base raspbian image with extra packages installed to run SCALP
            wget https://www.dropbox.com/s/1fsplxwzx71ufox/raspbian_small_backup.img?dl=0
            mv raspbian_small_backup.img?dl=0 raspbian.img
            sudo fdisk -l raspbian.img

            sudo mkdir -p /mnt/image/boot
            sudo mkdir -p /mnt/image/root

            # https://learnaddict.com/2016/02/23/modifying-a-raspberry-pi-raspbian-image-on-linux/
            sudo mount -v -o offset=4194304 -t vfat raspbian.img /mnt/image/boot
            sudo mount -v -o offset=50331648 -t ext4 raspbian.img /mnt/image/root

            cd /mnt/image/root/home/pi/

            echo $(ls)
            sudo rm -rf SCALPScripts
            sudo rm -rf Enamel
            sudo git clone https://github.com/PiETLab/SCALPScripts
            sudo mv SCALPScripts/SCALP.sh SCALPScripts/startSCALP.sh SCALPScripts/unmountDrive.sh SCALPScripts/changeconfig.sh SCALPScripts/config.txt .
            sudo mv SCALPScripts/enamel.desktop .config/autostart/
            sudo mv SCALPScripts/enamel_usb_autostart.rules /mnt/image/root/etc/udev/rules.d/

            spruce_type=SCALP
            wget $(curl -s https://api.github.com/repos/PiETLab/TreasureBoxBrailleApps/releases/latest | jq -r ".assets[] | select(.name | test(\"${spruce_type}\")) | .browser_download_url")
            unzip SCALP.zip && rm -rf SCALP.zip

            sudo umount /mnt/image/boot
            sudo umount /mnt/image/root

  build-apps:
    docker:
      # specify the version you desire here
      - image: jimador/docker-jdk-8-maven-node

    working_directory: ~/TreasureBoxBrailleApps

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: "SCALP and AuthoringApp - Build and Publish Release on GitHub"
          command: |
            now="$(date)"
            sudo apt-get install ant -y
            sudo apt install zip unzip
            npm install -g github-release-cli

            ant -f build.xml

            CIRCLE_TAG=Release-$(date '+%Y-%m-%d-%H-%M-%S')

            AUTHORING_APP_RELEASE_FILE=AUTHORING-APP
            ant -f jarBuildScripts/AuthoringApp.xml
            zip -r ${AUTHORING_APP_RELEASE_FILE}.zip ./Enamel/*
            rm -rf ./Enamel

            SCALP_RELEASE_FILE=SCALP
            ant -f jarBuildScripts/SCALP.xml
            cp -R FactoryScenarios ./Enamel/FactoryScenarios
            cp -R mbrola/mbrola.jar ./Enamel/mbrola.jar
            mkdir ./Enamel/USBBuffer && mkdir ./Enamel/logs
            zip -r ${SCALP_RELEASE_FILE}.zip ./Enamel/*
            rm -rf ./Enamel

            # github-release upload --owner ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name ${CIRCLE_TAG} --body "Release date: ${now}" ${SCALP_RELEASE_FILE}.zip ${AUTHORING_APP_RELEASE_FILE}.zip

workflows:
  version: 2
  build:
    jobs:
      - build-apps:
          filters:
            branches:
              only: master
      - build-raspbian-image:
          #requires:
          #  - build-apps
          filters:
            branches:
              only: master
