# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: jimador/docker-jdk-8-maven-node

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: "Build and Publish Release on GitHub"
          command: |
            sudo apt-get install ant -y
            sudo apt install zip unzip
            npm install -g github-release-cli
            VERSION=$(date +%s)
            RELEASE_FILE=${CIRCLE_PROJECT_REPONAME}-${CIRCLE_TAG}-build-${VERSION}
            mkdir bin
            ant -f build.xml
            zip -r ${RELEASE_FILE}.zip ./Enamel
            echo 11111111
            github-release upload --owner Daniel --user ${CIRCLE_PROJECT_USERNAME} --repo ${CIRCLE_PROJECT_REPONAME} --tag ${CIRCLE_TAG} --name ${CIRCLE_PROJECT_REPONAME}"."${CIRCLE_TAG}"-build-"${VERSION}".zip" --file ${RELEASE_FILE}.zip
